version: '3'

services:
  postgres:
    container_name: 'postgres_db'
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: "rusty"
      POSTGRES_USER: "rusty"
      POSTGRES_PASSWORD: "qwer"
#      PGDATA: /data/postgres
    volumes:
      - './src/resources/1-create.sql:/docker-entrypoint-initdb.d/1-create.sql'
      - './src/resources/2-fill.sql:/docker-entrypoint-initdb.d/2-fill.sql'
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"
    networks:
      - postgres
    restart: unless-stopped
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped
    env_file:
      - .env

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
